
["[-----AutoMessage Client Configuration-----]"]
	# 
	# LINKS = ["https://www.google.com", "https://www.yahoo.com"]
	LINKS = ["https://www.bisecthosting.com/lupin?r=automessage", "https://www.bisecthosting.com/lupin?r=automessage", "https://www.bisecthosting.com/lupin?r=automessage"]
	# 
	# Intervals should be spaced out if possible, to avoid repeat messages from file writing lag 
	# INTERVALS = [5, 10]
	INTERVALS = [5]
	# 
	# LIMITS = [3, 0]
	LIMITS = [1]
	# 
	# HARD LIMITS = [1, 1]
	HARD_LIMITS = [1]
	# Configuration in this file is for client-side only (i.e. "Thank you for downloading this modpack" being sent only once for the client, and never again)
	# !#! SET VALUES TO 0 OR "" IF UNUSED / NO LIMIT. !#! 
	# Color Name      Chat Color Codes
	# Dark Red        §4
	# Red             §c
	# Gold            §6
	# Yellow          §e
	# Dark Green      §2
	# Green           §a
	# Aqua            §b
	# Dark Aqua       §3
	# Dark Blue       §1
	# Blue            §9
	# Light Purple    §d
	# Dark Purple     §5
	# White           §f
	# Gray            §7
	# Dark Gray       §8
	# Black           §0
	# Reset           §r
	# 
	# MESSAGES = ["§2Thank you very much for downloading More Decorations§f", "§cDon't worry, this message will not appear again.§f"]
	MESSAGES = []

